name: Build llama.cpp

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (optional, but good practice for builds)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Build llama.cpp
        run: |
          cmake -B build -DLLAMA_CURL=OFF
          cmake --build build --config Release
